version: '3.8'

services:
  app:
    image: officialola/springdockerdemoone:0.0.1
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/springdockerdemo?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8.0.27
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: springdockerdemo
      MYSQL_USER: uername
      MYSQL_PASSWORD: password