
spring:
  datasource:
    url: jdbc:mysql://db:3306/springdockerdemo?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: officialola
    password: Integrity97@.
#    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update